### ISSUE TITLE
[FEATURE] 전역 상태관리 Redux 도입

### ISSUE THREAD

**Issue by Seojunhwan** [AndroidNetrunner/decrypto#42]
## ✨ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 상태관리를 위해 Redux 도입합니다!

## TODO

- [ ] Reducer Action, 필요한 payload 정의
- [ ] 기존 Room 컴포넌트 상태 변경 로직 Reducer 로 옮기기
- [x] #43

**Comment by Seojunhwan** [comment]
@AndroidNetrunner @Sara-Jo @071yoon 요거 이슈 관련해서 라벨이랑 내용 추가하실 거 있으시면 수정해주세요!
