### ISSUE TITLE
[FEATURE] 타이머 기능 부활

### ISSUE THREAD

**Issue by 071yoon** [AndroidNetrunner/decrypto#47]
## ✨ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 원래 있던 기능을 뺐는데, 이따 추가해봅시다

## TODO

- [ ] 타이머를 백엔드딴에서, 만약 받았으면 다시 안받게 수정하는 과정 필요?
- [ ] 아마 "" "" "" 을 주면, 백엔드에서 NULL 이라 판단을 안할테니 이러한 코드가 이미 있다면, 코드 갱신을 안하게 수정?
