### ISSUE TITLE
[BUG] 팀원이 제출 시 WAITING 안뜨는 버그

### ISSUE THREAD

**Issue by 071yoon** [AndroidNetrunner/decrypto#48]
## 🐛 Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 버그 개요

- 현재 우리팀이 제출 했을 때 나머지 팀원이 아무것도 안되는 상황이 와야됨
- 지금은 그냥 제출 가능한 형태임
- 연속으로 타다닥 제출하면 바로 터져버림

## TODO

- [ ] 우선 팀원이 제출하면 백엔드딴에서 다시 TEAM_WAIT 이라는 시그널을 팀 이름과 함께 보내줘야됨
- [ ] 그걸 받으면 프론트엔드에서는, 현재 WAIT 해야되는 애들을 해당화면을 보여주게 설정
