### ISSUE TITLE
[BUG] RoundResult 나올 때 힌트 순서가 이상하게 나옴

### ISSUE THREAD

**Issue by 071yoon** [AndroidNetrunner/decrypto#51]
## 🐛 Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 버그 개요

- 제곧내

## TODO

- [ ] 힌트 순서가 올바르게 나와야됨. 지금은 코드 순서로 나오는거 같음..??
