### ISSUE TITLE
[FEATURE] 게임중에 리더가 누구인지 확인

### ISSUE THREAD

**Issue by 071yoon** [AndroidNetrunner/decrypto#53]
## ✨ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 게임에서 누가 출제중인지 표시

- 기다리고 있으면 Waiting... 인데 ... 이 useState로다가 0.5초에 한번씩 올라가면 이쁠거 같다는 -> 준서님의 의견 

## TODO

- [ ] 리더 표시

- [ ] Waiting ... 애니메이션 추가
