### ISSUE TITLE
[FEATURE] 방장 표시기능

### ISSUE THREAD

**Issue by 071yoon** [AndroidNetrunner/decrypto#55]
## ✨ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 게임에서 내가 방장이다! 라는걸 보여주는 기능 필요

- 로비에서만 보여주면 될거같네요 

## TODO

- [ ] 아마 노란색 별모양으로 svg 를 만들면 되지 않을까 싶네요
