### ISSUE TITLE
[BUG?] bgm 다운 방식 변경

### ISSUE THREAD

**Issue by Seojunhwan** [AndroidNetrunner/decrypto#57]
## 🐛 Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 버그 개요

- 현재 BGM 은 서버측에서 다운 받고 있습니다.
- 용량은 접속 시 7메가 정도 다운받습니다~!
- 이를 aws s3 에서 다운받도록 변경하겠습니다~!

## TODO

- [ ] aws s3 에 저장된 bgm 주소를 드리겠읍니닷,,
- [ ] 적용만 해주십시오,,
