### ISSUE TITLE
[BUG] 🐛팀 바꾸면 왜 게임 안돼?

### ISSUE THREAD

**Issue by 071yoon** [AndroidNetrunner/decrypto#58]
## 🐛 Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 버그 개요

- 룸 페이지에서 팀을 바꾸면 게임이 잘 동작이 안되는 심각한 버그가 있습니다..

- 제가 생각했을때는, 팀을 바꾸는 과정에서 업데이트가 잘 안되거나, 리덕스에서 gameInfo 가 제대로 기입이 안됐을 가능성이 높다고 봅니다

- 왜냐! 소련팀이 코드를 제출 했을 때 미국팀이 코드를 제출했다고 판단을 하니까 개인 Redux 문제지 않을까..? 생각이 듭니다 [console.log 보면 DB 에서는 딱히 문제가 없어 보임]   

## TODO

- [ ] 열심히 콘솔로그 찍으면서 찾아봅시다... ㅜ
