### ISSUE TITLE
[BUG] Refresh 시 nginx 404 error 발생

### ISSUE THREAD

**Issue by Seojunhwan** [AndroidNetrunner/decrypto#60]
## 🐛 Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 버그 개요

- 홈페이지를 제외한 페이지에서 ex) https://decrypto.games/room 새로고침시 nginx 404 error 발생합니다.
- 사용자 경험 뚝떨
- refresh 후 게임 진행이 불가, index 페이지로 갔다와야 진행 가능
- backend 연결이 nginx 에서 `/` 로 되어있기에 `/api` 로 변경, 그로인해 socket 연결을 기존 `/` 에서 `/api` 로 변경합니다.
- nginx 측에선 `/api` 로 들어오는 요청은 `8080포트` 로 연결합니다.

## TODO

- [x] socket 연결 주소를 `/api` 로 변경
- [x] development 환경의 경우 연결 주소를 환경 변수로 지정
- [x] production 환경의 경우 `same-origin` 이므로 연결 주소를 `/api` 로 지정
