### ISSUE TITLE
[FEATURE] 팀원 목록 추가

### ISSUE THREAD

**Issue by AndroidNetrunner** [AndroidNetrunner/decrypto#65]
## ✨ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 게임 페이지에서 누구와 누구가 같은 팀인지 확인할 수 있도록 화면 왼쪽과 오른쪽에 팀원 목록을 띄울 예정입니다.

## TODO

- [ ] TeamMemberList라는 새로운 컴포넌트 만들기
