### ISSUE TITLE
[FEATURE] CodeGuess에서 두,세번째 단어부터 추측할 수 있도록 수정

### ISSUE THREAD

**Issue by AndroidNetrunner** [AndroidNetrunner/decrypto#66]
## ✨ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [ ] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

현재 CodeGuess에서는 첫 번째, 두 번째, 세 번째로 숫자를 고르면서, 고른 숫자를 제외하도록 되어있습니다.
이제 숫자들이 제외되지 않고, 제출을 눌렀을 때 유효한 코드(=3개의 숫자가 모두 다른 코드)인지를 검사하여 유효할 때만 제출하도록 만들 것입니다. (유효하지 않을 시 alert를 실행 후 코드 제출을 막습니다.)

## TODO

- [ ] CodeGuess의 숫자 부분을 수정해야 합니다.
- [ ] 다음 숫자를 얻는 함수 대신, 코드의 유효성 검사를 확인하는 함수를 만들어야 합니다.
