### ISSUE TITLE
[FEATURE] 게임이 끝난 후 메인 페이지로 이동하지 않기

### ISSUE THREAD

**Issue by AndroidNetrunner** [AndroidNetrunner/decrypto#67]
## ✨ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 게임 결과가 나온 후 바로 메인 페이지로 이동해 단어 기록을 확인할 수 없는 문제가 있습니다. 이제 게임이 끝나도 페이지에 머물러 확인할 수 있도록 있게 됩니다.

## TODO

- [ ] navigate('/')를 없애야 합니다.
