### ISSUE TITLE
[FEATURE] 숫자 신호

### ISSUE THREAD

**Issue by AndroidNetrunner** [AndroidNetrunner/decrypto#69]
## ✨ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 음성 채팅을 이용해 논의할 경우, 1번 단어, 2번 단어, 3번 단어 등으로 숫자를 말하게 됩니다. 이를 우리 팀과만 공유하기 위해, 리그 오브 레전드의 핑처럼 숫자 버튼을 활용해 팀원들에게 숫자 신호를 줄 수 있습니다.

## TODO

- [ ] 숫자 버튼 컴포넌트 생성
