### ISSUE TITLE
[COMPONENT] TimerOption

### ISSUE THREAD

**Issue by 071yoon** [AndroidNetrunner/decrypto#7]
## 🔨 Refactor Request check list

- [x] 이슈 제목: [COMPONENT] '컴포넌트 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 컴포넌트 설명

- 앞으로 게임을 진행시에, 게임의 진행시간을 예상하여 **팀장**이 선택 할 수 있게 설정
- 게임이 최대 32 rounds 로 진행된다
  - 문제 출제 및 코드 예측을 30초로 잡았을 때 게임의 평균 플레이타임이 10분에서 15분으로 예상됨 -> Medium
  - 한 라운드당 1분씩으로 잡으면 20분에서 30분으로 예상됨 -> Slow
  - 한 라운드당 15초 일시 5분에서 10분 사이에 끝날것으로 예상 -> Fast
  - 출제하는 시간과 예측하는 시간을 달리하여 선택권을 줘야할지 고민 (기본적으로 출제하는데 더 시간이 걸린다)
- 상위 컴포넌트: <Room />
- 컴포넌트 기능: 각 단계 제한시간 설정 및 예상 게임 시간 표시
- props 데이터: timeLimit(second)

## TODO

- [x] Captain 이 누구인지 알고 혼자 세팅할 수 있게 설정
- [x] 게임의 속도 Fast, Medium, Slow 정할 수 있게 설정
