### ISSUE TITLE
[BUG] 새로고침 및 연결 해제 후 재접속 불가

### ISSUE THREAD

**Issue by AndroidNetrunner** [AndroidNetrunner/decrypto#70]
## 🐛 Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 버그 개요

- 게임 도중 연결 해제나 새로 고침 등으로 나가질 경우, 게임 자체를 진행할 수 없는 문제가 생깁니다.
- 재접속 시 게임을 계속할 수 있도록 하는 기능이 필요합니다.

## TODO

- [ ] 연결해제된 유저의 정보 저장
