### ISSUE TITLE
[FEATURE]Docker, 백엔드, 프론트엔드 repo 통합

### ISSUE THREAD

**Issue by Seojunhwan** [AndroidNetrunner/decrypto#72]
## ✨ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- backend repo 와 frontend repo 통합 예정입니다.
- CD 구성 예정입니다.
- Docker 컨테이너 방식으로 배포예정입니다.
> 이미지만 넘기는 방식이 아닌 파일을 EC2 로 넘기고 EC2 에서 빌드 및 실행하는 환경으로 구성 예정입니다. 비효율적인 것 같은데 다른 방법을 잘 모르겠어요,,

## TODO

- [ ] Readme 파일 위치 변경
- [ ] 공통적으로 사용 예정인 파일 최상단으로 이동 필요 ex) Docker-compose,,
- [ ] Github Actions 를 통한 CD 구축 필요
- [ ] Docker 관련하여 설정 및 파일 구성 필요

**Comment by 071yoon** [comment]
도커와 CI/CD에 대한 스터디가 있으면 좋겠어요

**Comment by Seojunhwan** [comment]
> 도커와 CI/CD에 대한 스터디가 있으면 좋겠어요 @071yoon 

좋은 생각임다ㅏ,,!
